# Generated by Django 4.0.5 on 2022-06-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WalletAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
