# Generated by Django 4.0.5 on 2022-06-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WalletAPI', '0002_profile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallet',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='WalletAPI.wallet'),
        ),
    ]
