# Generated by Django 4.0.5 on 2022-06-07 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WalletAPI', '0003_profile_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
    ]
