# Generated by Django 4.0.5 on 2022-06-07 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WalletAPI', '0004_remove_wallet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='Wallet holder'),
        ),
    ]
