# Generated by Django 4.0.5 on 2022-06-07 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WalletAPI', '0007_remove_profile_wallet_remove_wallet_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='Profile',
            new_name='profile',
        ),
    ]
