# Generated by Django 4.0.5 on 2022-06-08 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WalletAPI', '0009_profile_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_holder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='WalletAPI.profile'),
        ),
    ]
